# This workflow uses actions that are not certified by GitHub.  They are
# provided by a third-party and are governed by separate terms of service,
# privacy policy, and support documentation.
#
# This workflow will install a prebuilt Ruby version, install dependencies, and
# run tests and linters.
name: "Ruby on Rails CI"
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      # We're using mysql 5.7 in production currently
      # TODO: We need to upgrade this in production because it's costing us extra AWS "support" dollars
      mysql:
        image: mysql:5.7
        ports:
          - "3306:3306"
        env:
          MYSQL_DATABASE: rails_test
          MYSQL_USER: rails
          MYSQL_PASSWORD: password
          MYSQL_ROOT_PASSWORD: rootpassword
        # Set health checks to wait until mysql has started
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 3
    env:
      RAILS_ENV: test
      DATABASE_URL: "mysql2://rails:password@127.0.0.1:3306/rails_test"
    steps:
      - name: Install tidy
        run: sudo apt install -y tidy
      - name: Checkout code
        uses: actions/checkout@v4
      # Add or replace dependency steps here
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@78c01b705fd9d5ad960d432d3a0cfa341d50e410 # v1.179.1
        with:
          bundler-cache: true
      # Add or replace database setup steps here
      - name: Set up database schema
        run: bin/rails db:schema:load
      # Add or replace test runners here
      - name: Run tests
        run: bin/rake

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@78c01b705fd9d5ad960d432d3a0cfa341d50e410 # v1.179.1
        with:
          bundler-cache: true
      - name: Generate binstubs
        run: bundle binstubs brakeman rubocop
      - name: Security audit application code
        run: bin/brakeman -q -w2
      - name: Lint Ruby files
        run: bin/rubocop --parallel
